defaults:
  - _self_
  - descriptors: [default]
  - preprocessing: [background_removal, text_removal]
  - evaluation: [default]

data:

  BBDD:
    path: ${hydra:runtime.cwd}/data/BBDD
    importation:

      descriptors:
        import_: False
        path: ${hydra:runtime.cwd}/data/descritptors/hogpyramial.pkl


    export:

      descriptors:
        save: True
        path: ${hydra:runtime.cwd}/data/descritptors/hogpyramial.pkl

  QN: qsd2_w3


  QS:
    path: ${hydra:runtime.cwd}/data/${data.QN}

    preprocessed:
      import_: True
      export_: True



    #importation:

    #   preprocessing:
    #    import_: False
    #    path: ${data.QS.path}/${data.QN}_processed.pkl

    #  descriptors:
    #    import_: False
    #    path: ${hydra:runtime.cwd}/data/descritptors

    #export:

    #  descriptors:
    #    export_: True
    #    path: ${hydra:runtime.cwd}/data/descritptors

    #  preprocessing:
    #    export_: True
    #    path: ${data.QS.path}/${data.QN}_processed.pkl